### ISSUE TITLE
Add Notifications

### ISSUE THREAD

**Issue by AndyTWF** [VATSIM-UK/uk-controller-api#8]
- Have a way of having notifications sent to the plugin, so that people can be informed about important things.

**Comment by BradleyDeLar** [comment]
Define "important things"? 

Some sort of two way communication may be required in order to mark a notification as "read" or at least "shown" so it doesn't appear again to a user... you would need to decide if that mark is done locally in the plugin or on the server through the api. 

How controllable do the notifications have to be? Will notifications always be sent to everyone or is there a requirement to send notifications just to DEL/GND/TWR/APP/CTR controllers.

Is push functionality expected or will the plugin check for notifications onload/every x seconds?
